### PR TITLE
Prepare for release

### PR DESCRIPTION
**Pull request by ddelange**
- [x] Reduce complexity / speed up import by switching to [`pypa/setuptools_scm`](https://github.com/pypa/setuptools_scm)
- [x] Fix crashing `%unload_ext` (full traceback below)
- [x] Add tests ([example test](https://github.com/ipython-contrib/IPython-extensions/blob/aa139bbd42dc6ca9999a1b4c593d245b457b6988/ipyext/tests/test_writeandexecute.py#L49))
- [x] Add GH CI/CD and run tests on all supported python versions ([example CI/CD](https://github.com/ddelange/pipgrip/blob/84a766dca193e8df45a2d45ac3fa4cda219fbcac/.github/workflows/main.yml#L16))

<details><summary>Traceback</summary>

```
$ ipython
Python 3.7.5 (default, Nov 28 2019, 13:19:54)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.13.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: %load_ext autotime
time: 382 µs

In [2]: %unload_ext autotime
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-bae2e3780b0d> in <module>
----> 1 get_ipython().run_line_magic('unload_ext', 'autotime')

~/.pyenv/versions/3.7.5/envs/vv/lib/python3.7/site-packages/IPython/core/interactiveshell.py in run_line_magic(self, magic_name, line, _stack_depth)
   2315                 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
   2316             with self.builtin_trap:
-> 2317                 result = fn(*args, **kwargs)
   2318             return result
   2319

</Users/david.de-lange/.pyenv/versions/3.7.5/lib/python3.7/site-packages/decorator.py:decorator-gen-65> in unload_ext(self, module_str)

~/.pyenv/versions/3.7.5/envs/vv/lib/python3.7/site-packages/IPython/core/magic.py in <lambda>(f, *a, **k)
    185     # but it's overkill for just that one bit of state.
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188
    189         if callable(arg):

~/.pyenv/versions/3.7.5/envs/vv/lib/python3.7/site-packages/IPython/core/magics/extension.py in unload_ext(self, module_str)
     49             raise UsageError('Missing module name.')
     50
---> 51         res = self.shell.extension_manager.unload_extension(module_str)
     52
     53         if res == 'no unload function':

~/.pyenv/versions/3.7.5/envs/vv/lib/python3.7/site-packages/IPython/core/extensions.py in unload_extension(self, module_str)
    105         if module_str in sys.modules:
    106             mod = sys.modules[module_str]
--> 107             if self._call_unload_ipython_extension(mod):
    108                 self.loaded.discard(module_str)
    109             else:

~/.pyenv/versions/3.7.5/envs/vv/lib/python3.7/site-packages/IPython/core/extensions.py in _call_unload_ipython_extension(self, mod)
    137     def _call_unload_ipython_extension(self, mod):
    138         if hasattr(mod, 'unload_ipython_extension'):
--> 139             mod.unload_ipython_extension(self.shell)
    140             return True
    141

~/git/ipython-autotime/autotime/__init__.py in unload_ipython_extension(ip)
     38
     39 def unload_ipython_extension(ip):
---> 40     ip.events.unregister('pre_run_cell', timer.start)
     41     ip.events.unregister('post_run_cell', timer.stop)
     42

~/.pyenv/versions/3.7.5/envs/vv/lib/python3.7/site-packages/IPython/core/events.py in unregister(self, event, function)
     76                 pass
     77
---> 78         raise ValueError('Function {!r} is not registered as a {} callback'.format(function, event))
     79
     80     def trigger(self, event, *args, **kwargs):

ValueError: Function <bound method LineWatcher.start of <autotime.LineWatcher object at 0x10c4a5f10>> is not registered as a pre_run_cell callback
time: 98.8 ms
```
</details>

### CODE REVIEW

**Comment by ddelange** [comment]
@cpcloud let me know what you think :)

I've added a simple test and CI/CD setup with basic flake8 and pytest. They're [passing on my fork](https://github.com/ddelange/ipython-autotime/pull/1/checks), and will start running here once merged.

I've deprecated `versioneer` in favour of the well-maintained alternative from `pypa`. It will populate the version string in `_version.py` when any form of `python setup.py` is run. So the file is in `.gitignore`, and will be written locally every time you `pip install`, or when Github Actions does the pypi upload.

So after merge, all we have to do is add PYPI_USERNAME `__token__` and PYPI_PASSWORD to https://github.com/cpcloud/ipython-autotime/settings/secrets, and create a Github Release with whatever tag (e.g. `v0.2` or `0.2.0` or so)

I don't have access to that link, nor maintainer rights on pypi somehow. Would you like to add them and publish a new Github Release?

**Comment by cpcloud** [comment]
@ddelange That all sounds good to me! Thanks for getting this done. I'm a little confused by the `__token__` stuff. To clarify the `secrets` should be:

```
PYPI_USERNAME: __token__
PYPI_PASSWORD: ?
```
not sure what the password should be, maybe I'm overthinking it?

**Comment by ddelange** [comment]
Exactly! The password will be an API token from someone with maintainer rights to the repo. You can create one here: https://pypi.org/manage/account/token

**Comment by cpcloud** [comment]
Done! Should we merge and give it a whirl?

**Comment by ddelange** [comment]
Let's go!

output

**Comment by cpcloud** [comment]
Dope, looks like this went off without a hitch. Great work @ddelange.

**Pull request merged**
